run: reorder functions according to name

diff --git a/run b/run
--- a/run
+++ b/run
@@ -50,25 +50,7 @@ cd $_PWD
 
 
 
-# reset to version
-function bvs_reset {
-TAG=$1
-git tag | grep -q -E "^$TAG$" || echo ">>> $TAG does not exist (list available tags with 'git tag')!"
-git tag | grep -q -E "^$TAG$" || exit 1
 
-STATUS=`git status --porcelain --ignore-submodules=all`
-[ -n "$STATUS" ] && echo ">>> UNCOMMITED LOCAL CHANGES, ABORTING (THEY WOULD BE LOST OTHERWISE)!" && exit 1
-
-BRANCH=`git rev-parse --abbrev-ref HEAD`
-REMOTE_BRANCH=`git rev-parse --abbrev-ref $BRANCH@{upstream}`
-LOCAL_COMMITS=`git rev-list --reverse $REMOTE_BRANCH..HEAD`
-
-echo ">>> STORING `echo \"$LOCAL_COMMITS\" | wc -l` LOCAL COMMIT(S)!"
-echo ">>> RESETTING TO $TAG!"
-git reset --hard $TAG
-echo ">>> CHERRY PICKING LOCAL COMMIT(S)!"
-echo "$LOCAL_COMMITS" | git cherry-pick --stdin
-echo ">>> DONE!"
 }
 
 
@@ -166,44 +148,25 @@ fi
 
 
 
-# setup
-function bvs_setup {
-echo
-echo ">>> SELECT modules to install!"
-while read LINE; do MODULES[${#MODULES[@]}]=$LINE; done < .bvsmodules
-for MOD in "${MODULES[@]}"
-do
-	eval MOD=($MOD)
-	NAME=${MOD[0]}
-	REPO=${MOD[1]}
-	[ -d modules/$NAME ] && echo ">>> SKIP $NAME!" && continue
-	echo
-	echo -e ">>> INSTALL $NAME ($REPO)? [y|N] \c"
-	read CMD
-	[ "$CMD"x != "yx" ] && echo ">>> SKIP $NAME!" && continue
-	git submodule add -f $REPO modules/$NAME
+# reset to version
+function bvs_reset {
+TAG=$1
+git tag | grep -q -E "^$TAG$" || echo ">>> $TAG does not exist (list available tags with 'git tag')!"
+git tag | grep -q -E "^$TAG$" || exit 1
 
-	[ ! -r modules/CMakeLists.txt ] && echo "# enable module compilation here (entries created by './run --new-module <MODULE>' or './run --setup')" > modules/CMakeLists.txt
-	if [ "${MOD[2]}" == "COLLECTION" ]
-	then
-		for i in modules/$NAME/*
-		do
-			[ ! -d $i ] && continue
-			MOD=${i/modules\/}
-			echo "#add_subdirectory($MOD)" >> modules/CMakeLists.txt
-		done
-	else
-		echo "#add_subdirectory($NAME)" >> modules/CMakeLists.txt
-	fi
-done
+STATUS=`git status --porcelain --ignore-submodules=all`
+[ -n "$STATUS" ] && echo ">>> UNCOMMITED LOCAL CHANGES, ABORTING (THEY WOULD BE LOST OTHERWISE)!" && exit 1
 
-git commit -m "WARNING: DO NOT PUSH THIS COMMIT TO THE DEVELOPMENT REPOSITORY!" &> /dev/null
+BRANCH=`git rev-parse --abbrev-ref HEAD`
+REMOTE_BRANCH=`git rev-parse --abbrev-ref $BRANCH@{upstream}`
+LOCAL_COMMITS=`git rev-list --reverse $REMOTE_BRANCH..HEAD`
 
-echo
-echo ">>> SETUP complete!"
-[ ! -d build ] && echo ">>> ADVICE: for out of source builds, consider using the directory 'build' (see Readme.txt)"
-echo ">>> ADVICE: Please modify modules/CMakeLists.txt to enable modules you want to add to compilation!"
-echo
+echo ">>> STORING `echo \"$LOCAL_COMMITS\" | wc -l` LOCAL COMMIT(S)!"
+echo ">>> RESETTING TO $TAG!"
+git reset --hard $TAG
+echo ">>> CHERRY PICKING LOCAL COMMIT(S)!"
+echo "$LOCAL_COMMITS" | git cherry-pick --stdin
+echo ">>> DONE!"
 }
 
 
@@ -242,6 +205,48 @@ done
 EOF
 
 eval "(cd $BASE_DIR/$BIN_DIR && $FIFO $GDB $GDBOPTS ./bvsd --bvs.config=$CONFIG)"
+}
+
+
+
+# setup
+function bvs_setup {
+echo
+echo ">>> SELECT modules to install!"
+while read LINE; do MODULES[${#MODULES[@]}]=$LINE; done < .bvsmodules
+for MOD in "${MODULES[@]}"
+do
+	eval MOD=($MOD)
+	NAME=${MOD[0]}
+	REPO=${MOD[1]}
+	[ -d modules/$NAME ] && echo ">>> SKIP $NAME!" && continue
+	echo
+	echo -e ">>> INSTALL $NAME ($REPO)? [y|N] \c"
+	read CMD
+	[ "$CMD"x != "yx" ] && echo ">>> SKIP $NAME!" && continue
+	git submodule add -f $REPO modules/$NAME
+
+	[ ! -r modules/CMakeLists.txt ] && echo "# enable module compilation here (entries created by './run --new-module <MODULE>' or './run --setup')" > modules/CMakeLists.txt
+	if [ "${MOD[2]}" == "COLLECTION" ]
+	then
+		for i in modules/$NAME/*
+		do
+			[ ! -d $i ] && continue
+			MOD=${i/modules\/}
+			echo "#add_subdirectory($MOD)" >> modules/CMakeLists.txt
+		done
+	else
+		echo "#add_subdirectory($NAME)" >> modules/CMakeLists.txt
+	fi
+done
+
+git commit -m "WARNING: DO NOT PUSH THIS COMMIT TO THE DEVELOPMENT REPOSITORY!" &> /dev/null
+
+echo
+echo ">>> SETUP complete!"
+[ ! -d build ] && echo ">>> ADVICE: for out of source builds, consider using the directory 'build' (see Readme.txt)"
+echo ">>> ADVICE: Please modify modules/CMakeLists.txt to enable modules you want to add to compilation!"
+echo
 }
 
 
